name: frii_site
description: kill me

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.15
  intl: ^0.18.0
  flutter_launcher_icons: "^0.14.4"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21